server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emaildb
    username: root
    password: ###
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: dummy
    password: dummy
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false


