server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: dummy
    password: dummy
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
cloud:
  aws:
    region:
      static: eu-central-1
    credentials:
      access-key: YOUR_ACCESS_KEY
      secret-key: YOUR_SECRET_KEY


